# SITE CONFIGURATION
baseurl: ""
url: "https://mmahsereci.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Blog                                   # site's title
description: "A website with blog posts and pages"      # used by search engines
avatar: assets/img/Frau_profile.jpg                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: >
     <p>Machine learning &nbsp; &bull; &nbsp; Statistics &nbsp; &bull; &nbsp; Random</p>
#     <p>Machine learning &nbsp; &#9679; &nbsp; Statistics &nbsp; &#9679; &nbsp; Random</p>
#     <p>Machine learning &nbsp; &#9734; &nbsp; Statistics &nbsp; &#9734; &nbsp; Random</p>
#     <p>Machine learning &nbsp; &starf; &nbsp; Statistics &nbsp; &starf; &nbsp; Random</p>
#     <p>Machine learning &bull; Statistics &bull; Other stuff.</p>
#     <p>Hi, and welcome.</p>
#     <p>Hi, and welcome. This is a tech blog.</p>
#  <p>  . </p>
#  <h1>Welcome</h1>
#  <p>  . </p>

#     <p>Enjoy.</p>
header_feature_image: "assets/img/projects/aurora_02.jpg"
#header_feature_image: assets/img/blog/Frau_centered2.jpg

footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
  &nbsp;&bull;&nbsp;
  Blog
  <a href="https://commons.wikimedia.org/wiki/Aurora#/media/File:Aurora_borealis_above_Storfjorden_and_the_Lyngen_Alps_in_moonlight,_2012_March.jpg">title image</a>
  by
  <a href="https://commons.wikimedia.org/wiki/User:Ximonic">Ximonic</a>
  [<a href="https://creativecommons.org/licenses/by-sa/3.0/">CC BY-SA 3.0</a>] cropped, flipped
  &nbsp;&bull;&nbsp;
  <a href="https://commons.wikimedia.org/wiki/File:Andromeda_Galaxy_M31_-_Heic1502a_10k.jpg">Search image</a>
  by ESA/Hubble under
  [<a href="https://creativecommons.org/licenses/by/4.0/deed.en">CC BY 4.0</a>]
  </br>Copyright <a href="https://github.com/mmahsereci">mmahsereci</a> © 2021

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
